FROM node:18.17.1

ENV CONTAINER_REGISTRY=fluxtubecontainerrepository.azurecr.io
ENV VERSION=1

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --omit=dev
COPY ./src ./src
COPY ./videos ./videos
CMD npm start